backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nume Preparat", name: "name", widget: "string"}
      - {label: "Categorie", name: "category", widget: "select", options: [
          "Pește",
          "Carne", 
          "Supe/Ciorbe",
          "Aperitive",
          "Salate",
          "Vinuri",
          "Băuturi",
          "Băuturi Alcoolice",
          "Garnituri",
          "Fructe de Mare",
          "Bere",
          "Cidru",
          "Deserturi",
          "Saramura"
        ]}
      - {label: "Porție", name: "portion", widget: "string"}
      - {label: "Preț", name: "price", widget: "number"}
      - {label: "Ingrediente", name: "ingredients", widget: "text"}
      - label: "Informații Nutriționale"
        name: "nutritionalInfo"
        widget: "object"
        fields:
          - {label: "Calorii", name: "calories", widget: "string", required: false}
          - {label: "Grăsimi", name: "fats", widget: "string", required: false}
          - {label: "Proteine", name: "protein", widget: "string", required: false}
          - {label: "Carbohidrați", name: "carbs", widget: "string", required: false}
          - {label: "Sare", name: "salt", widget: "string", required: false}
      - {label: "Alergeni", name: "allergens", widget: "string", required: false}
      - {label: "Aditivi", name: "additives", widget: "string", required: false}
